version: '3'
services:
  selenium:
    shm_size: 2g
    image: 'selenium/standalone-firefox:latest'
  tlscontact:
    image: 'virus/tlscontact-appointment-finder:latest'
    build: ./
    restart: on-failure
    volumes:
      - ./main.py:/usr/src/app/main.py
      - ./static:/usr/src/app/static
    depends_on:
      - selenium
